Repository paperback-community/general-extensions, pull requests merged in 2024-11, with the labels that each got.

#2 Updated the package.json repository URLs to the correct ones
  package.json
Labels: bug

#3 Improved the ESLint config
  eslint.config.js
  src/MangaDex/MangaDexHelper.ts
  src/MangaDex/MangaDexInterfaces.ts
  src/MangaDex/MangaDexParser.ts
  src/MangaDex/MangaDexSettings.ts
  src/MangaDex/SettingsForm.ts
  src/MangaDex/main.ts
Labels: enhancement

#4 Replicates commit 0a78957 from the template repository
  .github/workflows/bundle-deploy.yaml
  .github/workflows/test.yaml
Labels: enhancement

#6 Replicates commit 79d5381 from the template repository
  .github/workflows/test.yaml
Labels: bug

#5 Asura Scans Source Extension
  package-lock.json
  package.json
  src/Asura/AsuraConfig.ts
  src/Asura/AsuraHelper.ts
  src/Asura/AsuraInterceptor.ts
  src/Asura/AsuraParser.ts
  src/Asura/AsuraSettings.ts
  src/Asura/AsuraUtils.ts
  src/Asura/interfaces/Filters.ts
  src/Asura/main.ts
  src/Asura/pbconfig.ts
  src/Asura/static/icon.png
Labels: enhancement

#7 Added Asura Scans to the README
  README.md
Labels: enhancement

#18 Remove unimplemented cloudflare methods
  src/AsuraScans/main.ts
  src/AsuraScans/pbconfig.ts
Labels: enhancement

#16 Mgeko Fixes
  src/Mgeko/MgekoParser.ts
  src/Mgeko/main.ts
Labels: bug, enhancement
