Repository paperback-community/general-extensions, pull requests merged in 2025-03, with the labels that each got.

#104 Add MangaDex ratings and shareurl
  src/MangaDex/MangaDexParser.ts
  src/MangaDex/main.ts
  src/MangaDex/pbconfig.ts
Labels: enhancement

#109 Sort MangaDex filter tags
  src/MangaDex/external/tag.json
  src/MangaDex/pbconfig.ts
Labels: enhancement

#106 Addition of MangaKatana
  README.md
  src/MangaKatana/MangaKatana.d.ts
  src/MangaKatana/genreOptions.ts
  src/MangaKatana/genres.ts
  src/MangaKatana/main.ts
  src/MangaKatana/pbconfig.ts
  src/MangaKatana/static/icon.png
Labels: documentation, enhancement

#110 Add weebcentral
  README.md
  src/WeebCentral/WeebCentralConfig.ts
  src/WeebCentral/WeebCentralEnums.ts
  src/WeebCentral/WeebCentralHelper.ts
  src/WeebCentral/WeebCentralInterceptor.ts
  src/WeebCentral/WeebCentralParser.ts
  src/WeebCentral/interfaces/WeebCentralInterfaces.ts
  src/WeebCentral/main.ts
  src/WeebCentral/pbconfig.ts
  src/WeebCentral/static/icon.png
Labels: documentation, enhancement

#111 MangaDex qol
  eslint.config.js
  src/MangaDex/MangaDex.d.ts
  src/MangaDex/MangaDexParser.ts
  src/MangaDex/MangaDexSettings.ts
  src/MangaDex/external/tag.json
  src/MangaDex/main.ts
  src/MangaDex/pbconfig.ts
Labels: enhancement

#114 AsuraScans: Make IDs alphanumeric
  src/AsuraScans/AsuraHelper.ts
  src/AsuraScans/AsuraParser.ts
  src/AsuraScans/AsuraSettings.ts
  src/AsuraScans/main.ts
  src/AsuraScans/pbconfig.ts
Labels: bug

#115 Fix weebcentral IDs
  src/WeebCentral/WeebCentralHelper.ts
  src/WeebCentral/WeebCentralParser.ts
  src/WeebCentral/main.ts
  src/WeebCentral/pbconfig.ts
Labels: bug

#116 AsuraScans: Fix MangaDetails info
  src/AsuraScans/AsuraParser.ts
  src/AsuraScans/pbconfig.ts
Labels: bug

#119 Mgeko: Change how genre tag ids are set
  src/Mgeko/MgekoParser.ts
  src/Mgeko/pbconfig.ts
Labels: bug

#118 Add MangaDex Content Rating
  src/MangaDex/MangaDexParser.ts
  src/MangaDex/pbconfig.ts
Labels: enhancement

#120 Update Mangafire genres
  src/MangaFire/main.ts
Labels: bug

#121 MangaKatana URLBuilder fixes
  src/MangaKatana/main.ts
  src/MangaKatana/pbconfig.ts
Labels: bug

#124 Add ReaperScans Extension
  README.md
  src/ReaperScans/ReaperConfig.ts
  src/ReaperScans/ReaperInterceptor.ts
  src/ReaperScans/ReaperParser.ts
  src/ReaperScans/ReaperUtils.ts
  src/ReaperScans/interfaces/ReaperScansInterfaces.ts
  src/ReaperScans/main.ts
  src/ReaperScans/pbconfig.ts
  src/ReaperScans/static/icon.png
Labels: documentation, enhancement

#127 MangaKatana: Search by multiple genres support and made IDs alphanumeric
  src/MangaKatana/main.ts
  src/MangaKatana/pbconfig.ts
Labels: bug, enhancement

#131 Correct MangaPlus
  package-lock.json
  package.json
  src/MangaPlus/main.ts
  src/MangaPlus/pbconfig.ts
Labels: enhancement

#132 Add Webtoon Extension
  README.md
  package.json
  src/Webtoon/WebtoonI18NHelper.ts
  src/Webtoon/WebtoonInfra.ts
  src/Webtoon/WebtoonParser.ts
  src/Webtoon/WebtoonSettings.ts
  src/Webtoon/main.ts
  src/Webtoon/pbconfig.ts
  src/Webtoon/static/icon.png
Labels: enhancement

#133 Support % in id
  src/Webtoon/WebtoonParser.ts
  src/Webtoon/pbconfig.ts
Labels: bug

#134 Added the BatoTo Extension
  README.md
  src/BatoTo/BatoTo.d.ts
  src/BatoTo/SettingsForm.ts
  src/BatoTo/genreOptions.ts
  src/BatoTo/genres.ts
  src/BatoTo/helper.ts
  src/BatoTo/main.ts
  src/BatoTo/pbconfig.ts
  src/BatoTo/static/icon.png
Labels: documentation, enhancement

#138 WeebCentral: Fix recent section
  src/WeebCentral/WeebCentralParser.ts
Labels: bug

#137 Add mangapill source
  src/MangaPill/MangaPillConfig.ts
  src/MangaPill/MangaPillHelper.ts
  src/MangaPill/MangaPillInterceptor.ts
  src/MangaPill/MangaPillParser.ts
  src/MangaPill/main.ts
  src/MangaPill/pbconfig.ts
  src/MangaPill/static/icon.png
Labels: enhancement

#139 Mangapill: Refactor name and update README
  README.md
  src/Mangapill/MangapillConfig.ts
  src/Mangapill/MangapillHelper.ts
  src/Mangapill/MangapillInterceptor.ts
  src/Mangapill/MangapillParser.ts
  src/Mangapill/main.ts
  src/Mangapill/pbconfig.ts
  src/Mangapill/static/icon.png
Labels: documentation, chore

#142 MangaDex: Various improvements and additions
  src/MangaDex/MangaDex.d.ts
  src/MangaDex/MangaDexHelper.ts
  src/MangaDex/MangaDexInterceptor.ts
  src/MangaDex/MangaDexParser.ts
  src/MangaDex/MangaDexSettings.ts
  src/MangaDex/forms/ContentSettingsForm.ts
  src/MangaDex/forms/DiscoverSettingsForm.ts
  src/MangaDex/forms/GroupBlockForm.ts
  src/MangaDex/forms/LibraryMangaListForm.ts
  src/MangaDex/forms/MangaProgressForm.ts
  src/MangaDex/forms/SearchSettingsForm.ts
  src/MangaDex/forms/SessionInfoForm.ts
  src/MangaDex/forms/TrackingSettingsForm.ts
  src/MangaDex/forms/UpdateFilterSettingsForm.ts
  src/MangaDex/forms/WebsiteSettingsForm.ts
  src/MangaDex/forms/WebsiteStatusForm.ts
  src/MangaDex/main.ts
  src/MangaDex/pbconfig.ts
  src/MangaDex/providers/ChapterProvider.ts
  src/MangaDex/providers/CollectionProvider.ts
  src/MangaDex/providers/DiscoverProvider.ts
  src/MangaDex/providers/MangaProvider.ts
  src/MangaDex/providers/ProgressProvider.ts
  src/MangaDex/providers/SearchProvider.ts
  src/MangaDex/providers/SettingsProvider.ts
  src/MangaDex/utils/CommonUtil.ts
  src/MangaDex/utils/StateUtil.ts
Labels: enhancement
