Repository paperback-community/general-extensions, pull requests merged in 2025-05, with the labels that each got.

#162 MangaDex: Fix managed collections and minor improvements
  package-lock.json
  package.json
  src/MangaDex/MangaDexParser.ts
  src/MangaDex/MangaDexSettings.ts
  src/MangaDex/external/tag.json
  src/MangaDex/forms/SearchSettingsForm.ts
  src/MangaDex/forms/SessionInfoForm.ts
  src/MangaDex/main.ts
  src/MangaDex/pbconfig.ts
  src/MangaDex/providers/CollectionProvider.ts
  src/MangaDex/providers/SearchProvider.ts
Labels: bug, enhancement, dependencies

#167 Webtoon: fix Canvas and genre id
  src/Webtoon/WebtoonParser.ts
  src/Webtoon/main.ts
  src/Webtoon/pbconfig.ts
Labels: bug

#170 MangaDex: Fix unknown content ratings and add subtitle statistics and various changes
  src/MangaDex/MangaDexParser.ts
  src/MangaDex/MangaDexSettings.ts
  src/MangaDex/external/tag.json
  src/MangaDex/forms/ContentSettingsForm.ts
  src/MangaDex/forms/LibraryMangaListForm.ts
  src/MangaDex/forms/SearchSettingsForm.ts
  src/MangaDex/forms/TrackingSettingsForm.ts
  src/MangaDex/forms/UpdateFilterSettingsForm.ts
  src/MangaDex/main.ts
  src/MangaDex/pbconfig.ts
  src/MangaDex/providers/ChapterProvider.ts
  src/MangaDex/providers/CollectionProvider.ts
  src/MangaDex/providers/DiscoverProvider.ts
  src/MangaDex/providers/SearchProvider.ts
Labels: enhancement
