Repository paperback-community/general-extensions, pull requests merged in 2025-04, with the labels that each got.

#144 Change webtoon Ids
  src/Webtoon/WebtoonParser.ts
  src/Webtoon/main.ts
  src/Webtoon/pbconfig.ts
Labels: bug

#145 Webtoon: Remove debugging logs
  src/Webtoon/WebtoonI18NHelper.ts
  src/Webtoon/WebtoonParser.ts
  src/Webtoon/main.ts
  src/Webtoon/pbconfig.ts
Labels: chore

#149 Fix MangaDex Latest Updates Discover section pagination and add Artwork
  src/MangaDex/MangaDexParser.ts
  src/MangaDex/MangaDexSettings.ts
  src/MangaDex/forms/ContentSettingsForm.ts
  src/MangaDex/pbconfig.ts
  src/MangaDex/providers/DiscoverProvider.ts
  src/MangaDex/providers/MangaProvider.ts
Labels: enhancement

#147 AsuraScans: Fix title parsing in MangaDetails
  src/AsuraScans/AsuraParser.ts
  src/AsuraScans/pbconfig.ts
Labels: bug

#152 ComicK: Fix chapNum parsing
  src/ComicK/ComicKParser.ts
  src/ComicK/pbconfig.ts
Labels: bug

#153 Removed unused eslint-disable directives
  src/Webtoon/WebtoonI18NHelper.ts
Labels: chore

#154 MangaDex: Fix covers not loading
  src/MangaDex/MangaDexInterceptor.ts
  src/MangaDex/pbconfig.ts
Labels: bug

#156 MangaDex: Add Image Cropping and Fix Token Refresh Race Condition
  package-lock.json
  package.json
  src/MangaDex/MangaDexInterceptor.ts
  src/MangaDex/MangaDexParser.ts
  src/MangaDex/MangaDexSettings.ts
  src/MangaDex/forms/ContentSettingsForm.ts
  src/MangaDex/pbconfig.ts
  src/MangaDex/providers/ChapterProvider.ts
  src/MangaDex/utils/titleRelevanceScore.ts
Labels: bug, enhancement

#158 MangaDex: Automatically fix missing metadata and improved error handling
  src/MangaDex/MangaDexHelper.ts
  src/MangaDex/MangaDexInterceptor.ts
  src/MangaDex/MangaDexParser.ts
  src/MangaDex/forms/ContentSettingsForm.ts
  src/MangaDex/forms/UpdateFilterSettingsForm.ts
  src/MangaDex/main.ts
  src/MangaDex/pbconfig.ts
  src/MangaDex/providers/ChapterProvider.ts
  src/MangaDex/providers/CollectionProvider.ts
  src/MangaDex/providers/DiscoverProvider.ts
  src/MangaDex/providers/MangaProvider.ts
  src/MangaDex/providers/ProgressProvider.ts
  src/MangaDex/utils/BasicRateLimiter.ts
Labels: bug, enhancement

#157 Fixed MangaFox Download Issue
  src/MangaFox/MangaDemon.d.ts
  src/MangaFox/main.ts
  src/MangaFox/pbconfig.ts
Labels: bug

#163 [Webtoon] Fix space in genre
  src/Webtoon/WebtoonParser.ts
  src/Webtoon/pbconfig.ts
Labels: bug
