Repository paperback-community/general-extensions, pull requests merged in 2025-02, with the labels that each got.

#81 Add Mangafire & Manganelo Sources
  .github/dependabot.yml
  README.md
  src/MangaFire/MangaFire.d.ts
  src/MangaFire/MangaFireInterceptor.ts
  src/MangaFire/main.ts
  src/MangaFire/pbconfig.ts
  src/MangaFire/static/icon.png
  src/Manganelo/Manganelo.d.ts
  src/Manganelo/ManganeloInterceptor.ts
  src/Manganelo/main.ts
  src/Manganelo/pbconfig.ts
  src/Manganelo/static/icon.png
Labels: enhancement

#87 ComicK: Add back comic type search filter
  src/ComicK/ComicKParser.ts
  src/ComicK/main.ts
  src/ComicK/pbconfig.ts
Labels: enhancement

#89 Removal of Asura Scans Free
  README.md
  src/AsuraScansFree/AsuraScansFreeConfig.ts
  src/AsuraScansFree/AsuraScansFreeInterceptor.ts
  src/AsuraScansFree/AsuraScansFreeParser.ts
  src/AsuraScansFree/interfaces/AsuraScansFreeInterfaces.ts
  src/AsuraScansFree/main.ts
  src/AsuraScansFree/pbconfig.ts
  src/AsuraScansFree/static/icon.png
Labels: documentation, chore

#91 Removal of the template sync workflow
  .github/workflows/template-sync.yaml
  .templatesyncignore
Labels: chore

#96 Updated the installation link in the README
  README.md
Labels: documentation, chore

#94 Change discover section types
  src/AsuraScans/AsuraParser.ts
  src/AsuraScans/main.ts
  src/AsuraScans/pbconfig.ts
Labels: enhancement

#97 Update toolchain
  package-lock.json
  package.json
  src/Mgeko/main.ts
  src/Mgeko/pbconfig.ts
Labels: enhancement, dependencies

#103 ComicK: Fix since date fetching of new chapters
  src/ComicK/ComicKParser.ts
  src/ComicK/main.ts
  src/ComicK/pbconfig.ts
Labels: bug

#98 Add Mangadex and Manganelo search results sorting
  package-lock.json
  package.json
  src/MangaDex/MangaDexParser.ts
  src/MangaDex/main.ts
  src/MangaDex/pbconfig.ts
  src/Manganelo/main.ts
  src/Manganelo/pbconfig.ts
  src/utils/titleRelevanceScore.ts
Labels: enhancement
